#!/usr/bin/env sh

if [ $# -ne 1 ]
then
  echo "Usage: create <name>"
  exit 1
fi

REPO="$(echo "$1" | sed -e 's/\.git$//')"

case "$REPO" in
  *.* )
    echo "Repo name cannot contain periods"
    exit 1
    ;;
  */*/*/*/*/* )
    echo "Repo cannot be nested more than 4 times"
    exit 1
    ;;
esac

if [ -d "$REPO.git" ]
then
  echo "Repo already exists"
  exit 1
fi

mkdir -p "$REPO.git"
git init -q --bare "$REPO.git" || exit $?
echo "$REPO.git" >> repos

echo "Repo created at ~/$REPO.git"
