#!/usr/bin/env sh

if [ $# -ne 1 ]
then
  echo "Usage: delete <repo name>"
  exit 1
fi

REPO="$(echo "$1" | sed -e 's/\.git$//').git"

case "$REPO" in
  *.*.git )
    echo "Repo name cannot contain periods"
    exit 1
    ;;
  */*/*/*/*/*.git )
    echo "Repo cannot be nested more than 4 times"
    exit 1
    ;;
esac

if [ ! -d "$REPO" ]
then
  echo "Repo does not exist"
  exit 1
fi

rm -r "$REPO"
grep -v "$REPO" repos > new_repos
mv new_repos repos

echo "Repo at ~/$REPO deleted"
