#!/usr/bin/env sh

cat << EOF
Available commands:
  help               : show all available commands
  create <repo name> : create a new repository
  delete <repo name> : delete an existing repository
  list   [filter]    : list all repositories
  keys               : edit authorized_keys
EOF