#!/usr/bin/env sh

if [ $# -gt 1 ]
then
  echo "Usage: list [filter]"
  exit 1
fi

TOTAL=$(sort repos)

if [ $# -eq 0 ]
then
  OUT=$TOTAL
else
  OUT=$(grep "$1" repos | sort)
fi

TOTAL_COUNT=$(echo "$TOTAL" | wc -l)
COUNT=$(echo "$OUT" | wc -l)

if [ -z "$OUT" ]
then
  if [ -z "$TOTAL" ]
  then
    echo "You have no repositories."
  else
    echo "No results from $TOTAL_COUNT total repositories."
  fi
  exit 0
fi

cat << EOF
$OUT

Showing $COUNT of $TOTAL_COUNT total repositories.
EOF