#!/usr/bin/env sh

if [ $# -ne 2 ]
then
  echo "Usage: move <filter> <dst>"
  exit 1
fi

FILTERED="$(grep "^$1" repos)"
DST=$(echo "$2" | sed -e 's|/$||')
COUNT=$(echo "$FILTERED" | wc -l)

for src in $FILTERED
do
  REPO="$DST/$(basename -- "$src")"
  if [ -d "$REPO" ]
  then
    cat << EOF
Cannot move '$src' -> '$REPO'
Repo already exists at destination
EOF
    exit 1
  fi
done

echo "Moving $COUNT repositories:"

for src in $FILTERED
do
  REPO="$DST/$(basename -- "$src")"
  mkdir -p "$REPO"
  mv -v "$src" "$DST"
  sed -i repos -e "s|^$src$|$REPO|"
done
