#!/usr/bin/env sh

if [ $# -ge 1 ]
then
  if id "$1" > /dev/null 2>&1
  then
    echo "User already exists"
    exit 1
  fi
  name=$1
else
  while
    read -p "Username: " name
    [ -z "$name" ] || id "$name" > /dev/null 2>&1
  do [ -n "$name" ] && echo "User already exists"; done
fi

adduser "$name" -Dh "/srv/users/$name" -s /usr/bin/git-shell || exit $?
echo "$name:*" | chpasswd || exit $?

cat << EOF
Added user $name
Use 'keys $name' to add the user's public SSH keys
EOF