#!/usr/bin/env sh

if [ $# -ge 1 ]
then
  if ! id "$1" > /dev/null 2>&1
  then
    echo "User does not exist"
    exit 1
  fi
  name=$1
else
  while
    read -p "Username: " name
    [ -z "$name" ] || ! id "$name" > /dev/null 2>&1
  do [ -n "$name" ] && echo "User does not exist"; done
fi

while
  read -p "Remove home? [y/n]: " rhome
  [ "$rhome" != "y" ] && [ "$rhome" != "Y" ] && [ "$rhome" != "n" ] && [ "$rhome" != "N" ]
do true; done

if [ "$rhome" = "y" ] || [ "$rhome" = "Y" ]
then
  ERR=$(deluser --remove-home "$name" 2>&1) || { echo "$ERR"; exit $?; }
else
  ERR=$(deluser "$name" 2>&1) || { echo "$ERR"; exit $?; }
fi
